all: attack get_givens get_interps get_kept gvizify looper prover9-mace4
	mkdir -p ../bin
	cp attack ../bin
	cp get_givens ../bin
	cp get_interps ../bin
	cp get_kept ../bin
	cp gvizify ../bin
	cp looper ../bin
	cp prover9-mace4 ../bin
